name: Build Binary

on:
  push:
    branches:
      - master
  schedule:
    - cron: '20 13 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Setup permissions
        run: chmod +x ./hack/make.sh
      - name: Create Binary
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: sh ./hack/make.sh binary
